# Our docs are in mdbook format, so install that tool
# See
[tasks.install-mdbook]
install_crate = { crate_name = "mdbook", binary = "mdbook", test_arg = "--help" }


# We can use any diagram supported by kroki
# See: https://lib.rs/crates/mdbook-kroki-preprocessor
#    : https://kroki.io/
[tasks.install-mdbook-kroki]
install_crate = { crate_name = "mdbook-kroki-preprocessor", binary = "mdbook-kroki-preprocessor", test_arg = "--help" }

# We check all links
# See: https://github.com/Michael-F-Bryan/mdbook-linkcheck
[tasks.install-mdbook-linkcheck]
install_crate = { crate_name = "mdbook-linkcheck", binary = "mdbook-linkcheck", test_arg = "--help" }

# We can use Admonish markup, so install that tool
# See: https://lib.rs/crates/mdbook-admonish
[tasks.install-mdbook-admonish]
install_crate = { crate_name = "mdbook-admonish", binary = "mdbook-admonish", test_arg = "--help" }
script_runner = "@shell"
script = '''
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
mdbook-admonish install --css-dir src/assets/css/
'''

# We can make our own regex preprocessing templates
# See: https://lib.rs/crates/mdbook-regex
[tasks.install-mdbook-regex]
install_crate = { crate_name = "mdbook-regex", binary = "mdbook-regex", test_arg = "--help" }

# Automatically adds an "Edit this file on GitHub" to each page
# See: https://lib.rs/crates/mdbook-open-on-gh
[tasks.install-mdbook-open-on-gh]
install_crate = { crate_name = "mdbook-open-on-gh", binary = "mdbook-open-on-gh", test_arg = "--help" }


[tasks.install-docs-prereqs]
workspace = false
run_task = { name = [
        "install-mdbook-kroki",
        "install-mdbook-regex",
        "install-mdbook-admonish",
        "install-mdbook-open-on-gh",
        "install-mdbook-linkcheck"
    ], parallel = true }
dependencies = [
    "install-mdbook",
]

# Build and serve a live view of the POC Documentation
[tasks.view-docs]
workspace = false
category = "docs"
script_runner = "@shell"
script = '''
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
mdbook serve --open
'''

# Build and serve a live view of the POC Documentation
[tasks.build-mdbook]
workspace = false
category = "docs"
script_runner = "@shell"
script = '''
cd ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}
mdbook build
'''

[tasks.build-docs]
workspace = false
dependencies = [
    "build-mdbook"
]
