name: GitHub Pages

on:
  push:
    branches: 
      - "main"

    paths:
      - src/**
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - uses: taiki-e/install-action@v1
        with:
          tool: cargo-binstall,cargo-make,mdbook

      - name: Setup mdBook prerequisites 
        run: |
          cargo make install-docs-prereqs

      - name: Error on broken links
        run: |
          sed 's/warning-policy = "warn"/warning-policy = "error"/g' book.toml > book.toml

      - name: Build the book
        run: |
          cargo make build-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html